services:
  stm32_dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=${USERNAME:-vscode}
        - USER_UID=${USER_UID:-1000}
        - USER_GID=${USER_GID:-1000}
    volumes:
      - ..:/workspace:cached
    command: tail -f /dev/null
